export type SeedCourse = {
  modality: "bacharelado" | "licenciatura" | "tecnologo";
  name: string;
  duration: string;
  preview: string;
};

export const seedCourses: SeedCourse[] = [
  // Bacharelado
  { modality: "bacharelado", name: "Administração", duration: "3 anos", preview: "Gestão de empresas, pessoas e processos organizacionais." },
  { modality: "bacharelado", name: "Administração Pública", duration: "3 anos", preview: "Gestão de políticas públicas e instituições governamentais." },
  { modality: "bacharelado", name: "Arquivologia", duration: "3 anos", preview: "Organização, preservação e gestão de documentos e arquivos." },
  { modality: "bacharelado", name: "Biblioteconomia", duration: "3 anos", preview: "Gestão da informação, acervos e bibliotecas." },
  { modality: "bacharelado", name: "Ciências Contábeis", duration: "3 anos", preview: "Contabilidade, finanças e controle patrimonial." },
  { modality: "bacharelado", name: "Ciências Econômicas", duration: "3 anos", preview: "Análise econômica e políticas de mercado." },
  { modality: "bacharelado", name: "Ciências Imobiliárias", duration: "3 anos", preview: "Gestão e comercialização de imóveis e investimentos imobiliários." },
  { modality: "bacharelado", name: "Ciência Política", duration: "3 anos", preview: "Estudo de governos, partidos e relações políticas." },
  { modality: "bacharelado", name: "Educação Física", duration: "4 anos", preview: "Atividade física e esporte - Modalidade Semipresencial" },
  { modality: "bacharelado", name: "Museologia", duration: "3 anos", preview: "Gestão e preservação do patrimônio histórico e cultural." },
  { modality: "bacharelado", name: "Publicidade e Propaganda", duration: "3 anos", preview: "Criação, planejamento e gestão de campanhas publicitárias." },
  { modality: "bacharelado", name: "Relações Internacionais", duration: "3 anos", preview: "Comércio exterior, diplomacia e relações globais." },
  { modality: "bacharelado", name: "Teologia", duration: "3 anos", preview: "Estudos teológicos, religiosos e filosóficos." },
  { modality: "bacharelado", name: "Geografia", duration: "3 anos", preview: "Estudo do espaço geográfico, meio ambiente e sociedade." },
  { modality: "bacharelado", name: "Estatística", duration: "3 anos", preview: "Coleta, análise e interpretação de dados e indicadores." },
  { modality: "bacharelado", name: "Sociologia", duration: "3 anos", preview: "Análise das relações sociais e estruturas da sociedade." },
  { modality: "bacharelado", name: "Ciências Sociais", duration: "3 anos", preview: "Compreensão crítica da sociedade, cultura e política." },
  { modality: "bacharelado", name: "Química", duration: "3 anos", preview: "Estudo das substâncias, reações e aplicações químicas." },
  { modality: "bacharelado", name: "Ciências Biológicas", duration: "3 anos", preview: "Estudo da vida, ecossistemas e biotecnologia." },
  { modality: "bacharelado", name: "Física", duration: "3 anos", preview: "Fenômenos naturais, leis da física e aplicações tecnológicas." },
  { modality: "bacharelado", name: "Letras", duration: "3 anos", preview: "Estudo da linguagem, literatura e comunicação escrita." },
  { modality: "bacharelado", name: "Psicanálise", duration: "4 anos", preview: "Estudo da mente humana e das práticas psicanalíticas." },
  { modality: "bacharelado", name: "Engenharia de Dados", duration: "4 anos", preview: "Gestão, modelagem e análise de grandes volumes de dados." },
  { modality: "bacharelado", name: "Engenharia de Design Digital", duration: "4 anos", preview: "Criação de interfaces, produtos e experiências digitais." },
  { modality: "bacharelado", name: "Engenharia de Software", duration: "4 anos", preview: "Desenvolvimento e manutenção de sistemas e aplicativos." },
  { modality: "bacharelado", name: "Engenharia de Segurança Cibernética", duration: "3 anos", preview: "Proteção de sistemas, redes e dados digitais." },
  { modality: "bacharelado", name: "Engenharia DevOps", duration: "3 anos", preview: "Integração entre desenvolvimento e operações de software." },

  // Licenciatura
  { modality: "licenciatura", name: "Ciências Biológicas", duration: "4 anos", preview: "Formação em biologia e ciências" },
  { modality: "licenciatura", name: "Andragogia", duration: "4 anos", preview: "Educação de jovens e adultos" },
  { modality: "licenciatura", name: "Artes", duration: "4 anos", preview: "Ensino de artes e práticas artísticas" },
  { modality: "licenciatura", name: "Artes Visuais", duration: "4 anos", preview: "Formação em artes visuais" },
  { modality: "licenciatura", name: "Ciências da Religião", duration: "4 anos", preview: "Estudos religiosos e filosóficos" },
  { modality: "licenciatura", name: "Ciências Sociais", duration: "4 anos", preview: "Sociologia e ciências humanas" },
  { modality: "licenciatura", name: "Computação e Informática", duration: "4 anos", preview: "Ensino de tecnologia e informática" },
  { modality: "licenciatura", name: "Educação Especial", duration: "4 anos", preview: "Formação para educação inclusiva" },
  { modality: "licenciatura", name: "Educação Física", duration: "4 anos", preview: "Formação para ensino de educação física" },
  { modality: "licenciatura", name: "Filosofia", duration: "4 anos", preview: "Formação em pensamento filosófico" },
  { modality: "licenciatura", name: "Física", duration: "4 anos", preview: "Ensino de física e ciências exatas" },
  { modality: "licenciatura", name: "Geografia", duration: "4 anos", preview: "Geografia humana e física" },
  { modality: "licenciatura", name: "História", duration: "4 anos", preview: "Formação em história regional e mundial" },
  { modality: "licenciatura", name: "Letras - Língua Portuguesa e Libras", duration: "4 anos", preview: "Português e Língua Brasileira de Sinais" },
  { modality: "licenciatura", name: "Letras - Português e Espanhol", duration: "4 anos", preview: "Formação em português e espanhol" },
  { modality: "licenciatura", name: "Letras - Português e Francês", duration: "4 anos", preview: "Formação em português e francês" },
  { modality: "licenciatura", name: "Letras - Português e Inglês", duration: "4 anos", preview: "Formação em português e inglês" },
  { modality: "licenciatura", name: "Letras - Português e Italiano", duration: "4 anos", preview: "Formação em português e italiano" },
  { modality: "licenciatura", name: "Matemática", duration: "4 anos", preview: "Ensino de matemática" },
  { modality: "licenciatura", name: "Pedagogia", duration: "4 anos", preview: "Formação para atuar na educação infantil e anos iniciais" },
  { modality: "licenciatura", name: "Psicopedagogia", duration: "4 anos", preview: "Atuação em dificuldades de aprendizagem" },
  { modality: "licenciatura", name: "Química", duration: "4 anos", preview: "Ensino de química e práticas laboratoriais" },
  { modality: "licenciatura", name: "Sociologia", duration: "4 anos", preview: "Estudo das relações e estruturas sociais" },

  // Tecnólogo
  { modality: "tecnologo", name: "Análise e Desenvolvimento de Sistemas", duration: "2 anos", preview: "Programação e desenvolvimento de software" },
  { modality: "tecnologo", name: "Big Data e Inteligência Analítica", duration: "2 anos", preview: "Análise de grandes volumes de dados" },
  { modality: "tecnologo", name: "Cidades Inteligentes e Sustentáveis", duration: "1,5 anos", preview: "Tecnologia urbana e sustentabilidade" },
  { modality: "tecnologo", name: "Coaching e Desenvolvimento Humano", duration: "1,5 anos", preview: "Desenvolvimento pessoal e profissional" },
  { modality: "tecnologo", name: "Comércio Exterior", duration: "1,5 anos", preview: "Negócios internacionais" },
  { modality: "tecnologo", name: "Desenvolvimento Comunitário", duration: "1,5 anos", preview: "Projetos sociais e comunitários" },
  { modality: "tecnologo", name: "Design de Animação", duration: "1,5 anos", preview: "Criação de animações digitais" },
  { modality: "tecnologo", name: "Design de Interiores", duration: "1,5 anos", preview: "Concepção e decoração de ambientes" },
  { modality: "tecnologo", name: "Design de Produto", duration: "1,5 anos", preview: "Criação e desenvolvimento de produtos" },
  { modality: "tecnologo", name: "Design Gráfico", duration: "1,5 anos", preview: "Comunicação visual e branding" },
  { modality: "tecnologo", name: "Despachante Documentalista", duration: "2,5 anos", preview: "Documentação, registros e serviços cartoriais" },
  { modality: "tecnologo", name: "Embelezamento e Imagem Pessoal", duration: "1,5 anos", preview: "Estética e cuidados pessoais" },
  { modality: "tecnologo", name: "Empreendedorismo Educacional", duration: "1,5 anos", preview: "Inovação e gestão em educação" },
  { modality: "tecnologo", name: "Gerência em Saúde", duration: "1,5 anos", preview: "Gestão de serviços e unidades de saúde" },
  { modality: "tecnologo", name: "Gestão Comercial", duration: "1,5 anos", preview: "Vendas, trade e estratégias comerciais" },
  { modality: "tecnologo", name: "Gestão da Produção Industrial", duration: "2,5 anos", preview: "Processos e eficiência produtiva" },
  { modality: "tecnologo", name: "Gestão da Qualidade", duration: "1,5 anos", preview: "Controle e melhoria contínua" },
  { modality: "tecnologo", name: "Gestão da Tecnologia da Informação", duration: "2 anos", preview: "Governança e gestão de TI" },
  { modality: "tecnologo", name: "Gestão de Clínicas e Consultórios", duration: "1,5 anos", preview: "Administração de serviços de saúde" },
  { modality: "tecnologo", name: "Gestão de Cooperativas", duration: "1,5 anos", preview: "Administração cooperativista" },
  { modality: "tecnologo", name: "Gestão de Investimentos", duration: "1,5 anos", preview: "Finanças e mercado de capitais" },
  { modality: "tecnologo", name: "Gestão de Lojas e Pontos de Vendas", duration: "1,5 anos", preview: "Operação e gestão no varejo" },
  { modality: "tecnologo", name: "Gestão de Recursos Humanos", duration: "1,5 anos", preview: "Recrutamento, desenvolvimento e relações de trabalho" },
  { modality: "tecnologo", name: "Gestão de Registros e Informações em Saúde", duration: "1,5 anos", preview: "Prontuários e sistemas de informação em saúde" },
  { modality: "tecnologo", name: "Gestão de Segurança Privada", duration: "1,5 anos", preview: "Operação e gestão em segurança" },
  { modality: "tecnologo", name: "Gestão de Varejo", duration: "1,5 anos", preview: "Estratégias e operação varejista" },
  { modality: "tecnologo", name: "Gestão do Agronegócio", duration: "2,5 anos", preview: "Negócios agropecuários e gestão rural" },
  { modality: "tecnologo", name: "Gestão do Esporte", duration: "1,5 anos", preview: "Administração e eventos esportivos" },
  { modality: "tecnologo", name: "Gestão em Farmácia", duration: "1,5 anos", preview: "Administração de estabelecimentos farmacêuticos" },
  { modality: "tecnologo", name: "Gestão Financeira", duration: "1,5 anos", preview: "Finanças corporativas e planejamento" },
  { modality: "tecnologo", name: "Gestão Pública", duration: "2 anos", preview: "Administração e políticas públicas" },
  { modality: "tecnologo", name: "Internet das Coisas", duration: "2 anos", preview: "IoT, sensores e dispositivos conectados" },
  { modality: "tecnologo", name: "Investigação Forense e Perícia Jurídica", duration: "2,5 anos", preview: "Perícias e técnicas de investigação" },
  { modality: "tecnologo", name: "Jogos Digitais", duration: "2 anos", preview: "Desenvolvimento de games" },
  { modality: "tecnologo", name: "Logística", duration: "1,5 anos", preview: "Cadeia de suprimentos e operações" },
  { modality: "tecnologo", name: "Marketing", duration: "1,5 anos", preview: "Estratégias de mercado e marca" },
  { modality: "tecnologo", name: "Marketing Digital", duration: "1,5 anos", preview: "Publicidade e performance online" },
  { modality: "tecnologo", name: "Mediação, Conciliação e Arbitragem", duration: "1,5 anos", preview: "Resolução alternativa de conflitos" },
  { modality: "tecnologo", name: "Mídias Sociais e Digitais", duration: "1,5 anos", preview: "Gestão de conteúdo e comunidades online" },
  { modality: "tecnologo", name: "Ministério Pastoral", duration: "1,5 anos", preview: "Formação pastoral e liderança religiosa" },
  { modality: "tecnologo", name: "Negócios Imobiliários", duration: "1,5 anos", preview: "Mercado imobiliário e intermediação" },
  { modality: "tecnologo", name: "Negócios Sustentáveis e ESG", duration: "1,5 anos", preview: "Sustentabilidade e responsabilidade corporativa" },
  { modality: "tecnologo", name: "Processos Gerenciais", duration: "1,5 anos", preview: "Gestão administrativa e operacional" },
  { modality: "tecnologo", name: "Produção de Conteúdos Digitais", duration: "1,5 anos", preview: "Criação e edição de conteúdo online" },
  { modality: "tecnologo", name: "Recrutamento, Seleção e Desenvolvimento de Pessoas", duration: "1,5 anos", preview: "Gestão de talentos e desenvolvimento humano" },
  { modality: "tecnologo", name: "Redes de Computadores", duration: "2 anos", preview: "Infraestrutura e conectividade de redes" },
  { modality: "tecnologo", name: "Secretariado", duration: "1,5 anos", preview: "Assistência executiva e administração" },
  { modality: "tecnologo", name: "Segurança da Informação", duration: "2 anos", preview: "Proteção de dados e cibersegurança" },
  { modality: "tecnologo", name: "Segurança no Trabalho", duration: "2,5 anos", preview: "Saúde e segurança ocupacional" },
  { modality: "tecnologo", name: "Segurança no Trânsito", duration: "1,5 anos", preview: "Educação e gestão de segurança viária" },
  { modality: "tecnologo", name: "Segurança Pública", duration: "2 anos", preview: "Políticas e operações de segurança pública" },
  { modality: "tecnologo", name: "Serviços Jurídicos", duration: "1,5 anos", preview: "Atuação em escritórios e departamentos jurídicos" },
  { modality: "tecnologo", name: "Serviços Jurídicos e Notariais", duration: "1,5 anos", preview: "Atuação em cartórios e serviços notariais" },
  { modality: "tecnologo", name: "Serviços Penais", duration: "1,5 anos", preview: "Administração do sistema penitenciário" },
  { modality: "tecnologo", name: "Sistemas para Internet", duration: "2 anos", preview: "Desenvolvimento web e aplicações online" },
  { modality: "tecnologo", name: "Tradutor e Intérprete - Português-Francês", duration: "1,5 anos", preview: "Tradução e interpretação de idiomas" },
  { modality: "tecnologo", name: "Transformação Digital", duration: "2 anos", preview: "Transformação e inovação empresarial" },
  { modality: "tecnologo", name: "Inteligência Artificial", duration: "2 anos", preview: "Modelos, machine learning e aplicações" },
  { modality: "tecnologo", name: "Banco de Dados", duration: "2 anos", preview: "Modelagem e administração de bases de dados" },
  { modality: "tecnologo", name: "Processos Químicos", duration: "1,5 anos", preview: "Operação e controle de processos químicos" },
  { modality: "tecnologo", name: "Serviços Previdenciários", duration: "1,5 anos", preview: "Atendimento e gestão previdenciária" },
  { modality: "tecnologo", name: "Perícia Judicial e Extrajudicial", duration: "1,5 anos", preview: "Atuação pericial em diversas áreas" },
  { modality: "tecnologo", name: "Gestão da Atividade Policial", duration: "1,5 anos", preview: "Administração e operacionalização policial" },
  { modality: "tecnologo", name: "Criminologia", duration: "1,5 anos", preview: "Estudo do crime e políticas de prevenção" },
  { modality: "tecnologo", name: "Gastronomia", duration: "1,5 anos", preview: "Cozinha profissional e gestão culinária" },
  { modality: "tecnologo", name: "Turismo", duration: "1,5 anos", preview: "Gestão e operação no setor de turismo" },
  { modality: "tecnologo", name: "Produção Audiovisual", duration: "1,5 anos", preview: "Criação e produção de conteúdo audiovisual" },
];
